import { Lato, Poppins } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/NavigationBar";
import Footer from "@/components/Footer";

const lato = Lato({
  variable: "--font-Lato",
  weight: ["100", "400", "700"],
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-Poppins",
  weight: ["100", "200", "300", "400", "500", "600"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Ecorus",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} ${poppins.variable} antialiased`}
      >
        <NavigationBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
